version: '3'

services:
  synapsis-be-assignment:
    image: synapsis_be_assignment
    container_name: synapsis-be-assignment
#    network_mode: todo_list_network
    restart: always
    ports:
      - 8082:8082
    volumes:
      - ./config/yaml:/opt/synapsis-be-assignment/config/yaml